language: python
cache: pip
sudo: false
matrix:
  include:
  - env: TOXENV=py27-dj110-w111
    python: 2.7
  - env: TOXENV=py35-dj110-w111
    python: 3.5
  - env: TOXENV=py36-dj110-w111
    python: 3.6  
  - env: TOXENV=py36-dj111-w111
    python: 3.6
install:
- pip install tox coveralls
script:
- tox
after_success: coveralls
